export const CREATE_SUBJECT = "CREATE_SUBJECT";
export const LOAD_SUBJECTS_SUCCESS = "LOAD_SUBJECTS_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const CREATE_SUBJECT_SUCCESS = "CREATE_SUBJECT_SUCCESS";
export const UPDATE_SUBJECT_SUCCESS = "UPDATE_SUBJECT_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_SUBJECT_OPTIMISTIC = "DELETE_SUBJECT_OPTIMISTIC";
